image: "artifactory-gojek.golabs.io:6555/cx-node:12.13.0"

stages:
  - pages

cache:
  paths:
    - node_modules/
pages:
  stage: pages
  script:
    - yarn install
    - yarn build
    - yarn build-storybook --quiet
  artifacts:
    paths:
      - build
  when: manual
